package com.hdu.miaoshaserver.dao;

import com.hdu.miaoshaserver.dataobject.UserPasswordDo;
import org.springframework.stereotype.Component;

@Component(value = "UserPasswordDoMapper")
public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    UserPasswordDo selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDo record);
}