package com.hdu.miaoshaserver.dao;

import com.hdu.miaoshaserver.dataobject.UserDO;
import org.springframework.stereotype.Component;

//该注解是解决idea mapping注入时显示could not autowire， no beans type of UserDOMapper found
@Component(value = "UserDOMapper")
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    UserDO selectByPrimaryKey(Integer id);

    UserDO selectByTelphone(String telphone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Web Febr 05 17:01:32 CST 2020
     */
    int updateByPrimaryKey(UserDO record);
}